### ISSUE TITLE
randomly assigned /sys/class/hwmon

### ISSUE THREAD

**Issue by jamieson-olsen** [algirdasc/t3600_fancontrol#1]
Thanks for this utility. It really helps the braindead temperature control in the T3600. Every time my T3600 machine boots up the three hwmon modules in /sys/class/hwmon are randomly assigned. For example, /sys/class/hwmon/hwmon1/pwm1 is present now, but next boot it may not exist, and instead show up in  /sys/class/hwmon/hwmon2. Do you know of any way to lock this down so it's always the same?

**Comment by algirdasc** [comment]
No, sorry, I don't have t3600 anymore. But you could solve this by iterating all hwom/* items and applying same logic to all.
